language: generic
sudo: false
install:
    - git clone https://github.com/thinca/vim-themis && (cd vim-themis && git show HEAD)
    - git clone https://github.com/Shougo/vimproc.vim.git && (cd vimproc.vim && git show HEAD && make)
before_script:
    - uname -a
    - vim --version
script:
    - ./vim-themis/bin/themis test/
