language: generic
install:
    - git clone https://github.com/thinca/vim-themis
    - git clone https://github.com/junegunn/vim-emoji.git
    - git clone https://github.com/Shougo/vimproc.vim.git
    - cd vimproc.vim/ && make
before_script:
    - uname -a
    - vim --version
    - echo ja_JP.UTF-8 UTF-8 | sudo tee -a /var/lib/locales/supported.d/local
    - echo ja_JP.UTF-8 UTF-8 | sudo tee -a /etc/locale.gen
    - sudo /usr/sbin/locale-gen
script:
    - ./vim-themis/bin/themis test/
